### ISSUE TITLE
sign up 수정

### ISSUE THREAD

**Issue by kjy11** [hy-kiera/hotel_manage#22]
패스워드를 제외한 정보는 테이블에 따로 저장하고 아이디와 패스워드는 django자체의 admin 서비스로 보내지도록 수정이 필요합니다.

**Comment by ChaeLinYeo** [comment]
https://teamlab.github.io/jekyllDecent/blog/tutorials/Django-Admin-커스터마이징
이거보고 한번 해볼게요..!

**Comment by ChaeLinYeo** [comment]
https://teamlab.github.io/jekyllDecent/blog/tutorials/Django-Admin-커스터마이징
요거 참고해볼게요~~
![2018-11-27 2 58 14](https://user-images.githubusercontent.com/29560815/49061836-40511e00-f255-11e8-9ac7-416b6062cf6a.png)

user어디서 수정할 수 있는지 찾아봐야함.

**Comment by kjy11** [comment]
일단 포크된 제 repository sign_up branch에 올려놨습니다.
